### PR TITLE
GRW-463 / Feature / Add new AmountCollection section

### PR DESCRIPTION
**Pull request by robinandeer**
## What?

Add storybook stories.
Provide default value in useFeature hook to make it work with storybook.
Add new HeadingXS component from design system.
Integrate amount collection on offer page
Update tooltip to new design, remove size option.
Align perils right edge to the rest of content.
Remove old "Limits" component.

## Why?

Follow up on offer page design updates from Zak.

## Demo

Screenshot 2021-10-21 at 13 43 13

Screenshot 2021-10-21 at 13 47 18

_Referenced ticket(s): [GRW-463]_

[GRW-463]: https://hedvig.atlassian.net/browse/GRW-463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mehdielket — DISMISSED** [review]
Well done. Nice and clean! 😊

**Review by gustaveen — COMMENTED** [review]
Looks great! Nice that you added it to storybook as well 🙌 Just had a comment on the use of grid

**Review by styrelius — COMMENTED** [review]
Nice 👍 I don't know if we care (IMO we probably shouldn't) but it looks a bit weird with those full width elements on tablet:
Screenshot 2021-10-27 at 11 04 25

**Review by styrelius — APPROVED** [review]
OK just a thought 👇  but you can ignore it if you want to 😇 Great job with this!

**Pull request merged**
