### PR TITLE
GRW-1002 / feat / Add car info to Offer page's hero

### PR DESCRIPTION
**Pull request by simonauner**
## What?

This PR adds Car info to Offer page's Hero, if available in list of quotes.

The data that we get from VTR is a bit sketchy - sometimes either `makeAndModel` or `model` are empty, and sometimes they contain duplicate information.

Some examples from Fredrik L:

```
makeAndModel: TOYOTA T27
model: TOYOTA AVENSIS
```
```
makeAndModel: PEUGEOT L
model: 308
```
```
makeAndModel: VOLVO
model: XC60 T8 TWIN ENGINE
```
```
makeAndModel: HYUNDAI I20 1.4 A4COMFOR
model: I20
```
```
makeAndModel: VOLVO M + V50
model: null
```

That's why the `getCarMakeAndOrModel` method does some splitting, filtering and joining.

## Why?

This is added so that users know which car they've been given a quote for.

**Ticket(s): [GRW-1002]**

image

image

[GRW-1002]: https://hedvig.atlassian.net/browse/GRW-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by simonauner** [comment]
See my question regarding the types (this is what fails the build): https://hedviginsurance.slack.com/archives/G01MARCFUUW/p1652164823836129

**Comment by simonauner** [comment]
I added a `as SwedishCarDetails` and that solved the problem. We still access a property that's deprecated, but that's where the data exists 🤷

**Review by robinandeer — COMMENTED** [review]
Are we sure this information is not also passed in the "data" field? That's how it was supposed to work 🤔

**Comment by simonauner** [comment]
> Are we sure this information is not also passed in the "data" field? That's how it was supposed to work 🤔

That was my impression as well! Maybe I am missing something in a request or something needs to be done in Giraffe? This is the PR that added SwedishCarInfo to Giraffe: https://github.com/HedvigInsurance/giraffe/pull/1573

image

**Review by robinandeer — APPROVED** [review]

**Pull request merged**
