### PR TITLE
Add CODEOWNERS file

### PR DESCRIPTION
**Pull request by robinandeer**
## What?

Add CODEOWNERS file.

## Why?

Automatically request review when someone opens a pull request.

Ref: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners#about-code-owners

### CODE REVIEW

**Review by styrelius — APPROVED** [review]
Nice! 😀

**Comment by robinandeer** [comment]
Or should it be @HedvigInsurance/clients instead? Is it too narrow with only "www"?

**Comment by styrelius** [comment]
> Or should it be @HedvigInsurance/clients instead? Is it too narrow with only "www"?

No I think **WWW** is enough - no need _always_ ask the app team for review on the web-onboarding. I think. (But we should probably be better at requesting reviews from them when we do something that potentially affects them though)

**Comment by robinandeer** [comment]
Right, that's true. Especially until they migrate to their own Embark-clients

**Pull request merged**
