### PR TITLE
Kill lottie typing animation in favor of pure-css animation

### PR DESCRIPTION
**Pull request by palmfjord**
☝️
Lottie takes up about 200KB (non-gz), and even if we're code splitting it's used in a critical path so it needs to load before the user can do anything. I see no reason to use it for an animation this simple. But let's keep the `LazyLottie` component in case we want to use it later?

### CODE REVIEW

**Comment by Iamsamwhoami** [comment]
@palmfjord could we maybe build this with `animated`? then we can get rid of the typing animation being a Lottie in the app as well :)

**Comment by hedvigoscar** [comment]
I like this idea! Then we could probably use `react-native-animated-components` as well for web which would be really cool.

**Comment by Iamsamwhoami** [comment]
@palmfjord yes, I was to write that yesterday, have we hooked this up to heroku? so that I can see how it looks.

**Comment by palmfjord** [comment]
@Iamsamwhoami i'm afraid you'll have to run it locally, since the giraffe is down atm

**Pull request merged**
