### PR TITLE
Forever intro screens

### PR DESCRIPTION
**Pull request by palmenhq**
Screenshot 2020-06-29 at 15 52 25
Screenshot 2020-06-29 at 15 52 18

### CODE REVIEW

**Comment by gustaveen** [comment]
Don't know if I setup the route wrong but the background is white for me 
Screenshot 2020-06-30 at 10 24 31

**Comment by gustaveen** [comment]
Screenshot 2020-06-30 at 11 28 53
Maybe just remove the active styling on the overlay nav buttons.

**Review by gustaveen — DISMISSED** [review]
Really nice! 😍 Just some fixes that you can address in a new PR if you want to

**Comment by palmenhq** [comment]
@gustaveen probably it neeeds to be wrapped in something, we can look at it together if you want :)

**Review by gustaveen — APPROVED** [review]

**Pull request merged**
