### PR TITLE
Remove `MemberOffer` query (unused)

### PR DESCRIPTION
**Pull request by robinandeer**
## What?

...and regenerate GraphQL client.

## Why?

It's not used anywhere.

### CODE REVIEW

**Review by gustaveen — DISMISSED** [review]
🧹 👌

**Comment by robinandeer** [comment]
@gustaveen @guilhermespopolin I forgot that this will make firstName/lastName optional in our GraphQL client -- so now I'm not sure if we should merge this already...? Any input?

**Comment by guilhermespopolin** [comment]
> @gustaveen @guilhermespopolin I forgot that this will make firstName/lastName optional in our GraphQL client -- so now I'm not sure if we should merge this already...? Any input?

True 🤔 
This change on backend side is already in production. And I've been testing it on Mehdi's PR. I guess it's ok to merge it.

**Comment by robinandeer** [comment]
Okey cool! Our assumptions where correct then -- I'll update this PR so it can be merged :)

**Review by guilhermespopolin — DISMISSED** [review]

**Review by styrelius — APPROVED** [review]
🗿

**Pull request merged**
