### PR TITLE
[HVG-156] Fixed on submit not firing in Checkout

### PR DESCRIPTION
**Pull request by virrios**
Norway: Not possible to sign on Android

Added onSubmit function and hidden input field to trigger sign.

### CODE REVIEW

**Review by gustaveen — APPROVED** [review]
Great job! @virrios 🥳

**Comment by gustaveen** [comment]
Unrelated to the issue, it got me thinking when testing this, if we should move the date picker to the top? So adding your ssn and submitting is the last input? Also the datepicker is missing it's label

**Comment by palmenhq** [comment]
@gustaveen which date picker? 😅

**Comment by gustaveen** [comment]
This one (where it says Idag) 🙂  
Might be a bit unclear what the date is for if we don't show a label @palmenhq 
Screenshot 2020-10-27 at 13 48 09

**Comment by styrelius** [comment]
I agree with @gustaveen that the date picker should be moved to the top, since it has to do with the insurance you're signing up for it's in my mind reasonable to have it grouped with the type of insurance and price. Also,  yes, a label would be neat!

**Comment by virrios** [comment]
I agree, I was confused what the date was for! Should this change be part of this pr or are we handling it as an unrelated issue?

**Comment by styrelius** [comment]
It's probably good to have that as another issue right?

**Comment by virrios** [comment]
I agree, I think that makes the most sense

**Pull request merged**
