### PR TITLE
GRW-471 / Fix / Update all variant quotes when changing personal information

### PR DESCRIPTION
**Pull request by mehdielket**
## What?

This fixes the following:
* Personal information not updating on the Accident Quote
* Updating all quotes that are part of the variants (even the ones that are not selected) when personal info is changed

## Why?

When a user changes their personal info, this should be reflected on all the quotes even the ones that are not part of the current selected bundle.

_Referenced ticket(s): [GRW-471]_

https://user-images.githubusercontent.com/89857278/138673378-c1c3f34c-328b-4b42-8147-37a45f95375f.mov

[GRW-471]: https://hedvig.atlassian.net/browse/GRW-471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by robinandeer — DISMISSED** [review]
Amazing job -- this really is one of the trickiest parts of the code base 💪 

Do let @styrelius have a look as well since she knows it best (I think).

But for me it looks good. Will test it locally as well.

**Review by guilhermespopolin — DISMISSED** [review]
LGTM. Although my opinion is almost nullish at the moment 😬

**Review by styrelius — COMMENTED** [review]
Good job! 👍 Just some suggestions below

**Review by robinandeer — DISMISSED** [review]
LGTM! Let's investigate how app is handling this in a more generic way asap 😅

**Review by robinandeer — APPROVED** [review]
Good work!

**Pull request merged**
