### PR TITLE
forever page light theme

### PR DESCRIPTION
**Pull request by dendoesit**
## What?

Forever page light theme

## Why?

Align to brand
https://web-onboardi-grw-667-fo-maw2fk.herokuapp.com/se-en/forever

Zak confirmed.

**Ticket(s): []**
(https://hedvig.atlassian.net/browse/GRW-667)

image

### CODE REVIEW

**Comment by robinandeer** [comment]
There's a few elements that are invisible now on the page 😅 -- the link in the footer text as well as the language toggle.

Screenshot 2021-12-17 at 09 39 05

The footer text also fails accessibility -- not enough contrast between foreground/background.

Screenshot 2021-12-17 at 09 39 20

**Comment by robinandeer** [comment]
nit: something that isn't anything new is to also add a placeholder to the input, I think that's missing today

**Review by gustaveen — APPROVED** [review]
👍

**Review by robinandeer — CHANGES_REQUESTED** [review]
Like I mentioned in my comments -- currently, links and languages switcher are not visible on page so need to fix that before merge :)

**Comment by dendoesit** [comment]
The review link is updated. Added the color change to language picker. 
The input field contains a placeholder but it's currently empty. Do you know what a code example looks like so I can put it inside @robinandeer  ?

**Comment by gustaveen** [comment]
Ah good catch, missed the language picker 🙌 We should use the same styling as the footer component you added in Embark for the paragraph and link. @dendoesit 

Screenshot 2021-12-17 at 13 23 08

**Comment by robinandeer** [comment]
> The review link is updated. Added the color change to language picker.
> The input field contains a placeholder but it's currently empty. Do you know what a code example looks like so I can put it inside @robinandeer ?

I believe this could be a good placeholder example: `7VEKCAG`

**Review by robinandeer — DISMISSED** [review]
Cool! I think this works 🦾 

I still think the overall look of the page is a bit dull with the new theme -- but that's maybe something for @zakkjellin to look into in the future!

**Comment by dendoesit** [comment]
It is my understanding that Zak plans to do a redesign on this but it's just not a priority right now. 

added @gustaveen's input and the placeholder 👍

**Review by robinandeer — APPROVED** [review]
Nice updates!

**Pull request merged**
