### PR TITLE
Align price and title label in sidebar

### PR DESCRIPTION
**Pull request by robinandeer**
## What?

Use standard media queries.
Use the same line-height for labels that need to align.
Override global margin (h3).

## Why?

Before the labels were centered which looked strange when the title wraps on two lines.
Changed some line heights to share the same value so they align better.

### Before

image

### Sidebar mobile + desktop

Screenshot 2021-05-24 at 11 12 59
Screenshot 2021-05-24 at 11 13 09

### Compare component

Screenshot 2021-05-24 at 11 11 27

### Checkout modal mobile + desktop

Screenshot 2021-05-24 at 11 09 19
Screenshot 2021-05-24 at 11 09 31

### CODE REVIEW

**Review by styrelius — COMMENTED** [review]
Neat! 🌻 

On super small screens the price div overflows a lot now (which it currently only does a little heh) and I don't know if we care since very few people have those phones anymore, but _if_ we want to do something about it I suggest a `flex-wrap: wrap;` and `justify-content: flex-end;` on `PriceNumbers` div

currently: 
image

with wrap:
Screenshot 2021-05-24 at 12 01 41

**Comment by robinandeer** [comment]
This could also be an alternative solution

Screenshot 2021-05-24 at 17 47 12

Ping @styrelius - what do you say?

**Comment by styrelius** [comment]
Wow, so sorry for being extremely slow on this! Your solution looks nicer I think! 👍 🎨

**Comment by robinandeer** [comment]
@styrelius haha thanks! I was thinking to peer-review this and some other PRs -- easier sometimes!

I had some issues getting the discount-label to align properly though -- will upload screenshots of that!

**Comment by robinandeer** [comment]
## Very small

Screenshot 2021-05-27 at 17 10 17

## Small

Screenshot 2021-05-27 at 17 09 42

## Large

Screenshot 2021-05-27 at 17 10 30

**Review by styrelius — DISMISSED** [review]
💅 🎨 👍

**Comment by robinandeer** [comment]
Okey now I hope this is up to design specs! :D

Lots of examples in different viewport sizes.

The "Hedvig Forever"-badge looks strange on small screens but pls disregard for the sake of this PR!

Screenshot 2021-06-01 at 13 54 32

Screenshot 2021-06-01 at 13 54 24

Screenshot 2021-06-01 at 13 54 15
Screenshot 2021-06-01 at 13 54 00
Screenshot 2021-06-01 at 13 53 44
Screenshot 2021-06-01 at 13 53 31
Screenshot 2021-06-01 at 13 53 18

**Comment by gustaveen** [comment]
Awesome work @robinandeer 🎉 It's a hassle to align this for all use cases, well done! On tiny thing that might be worth adding, if you agree and it doesn't break anything else :D, is setting aligning `Header` to the baseline. In that way the discount would align along that baseline as well. Also really neat feature Chrome added to devtools when inspecting alignment! 🎉


https://user-images.githubusercontent.com/6661511/120338095-2eec9f00-c2f4-11eb-9386-3d2d77a9acbd.mov

**Review by gustaveen — DISMISSED** [review]

**Comment by robinandeer** [comment]
> On tiny thing that might be worth adding, if you agree and it doesn't break anything else :D, is aligning `Header` to the baseline.

That's super nice -- seems to work really well!

**Review by styrelius — APPROVED** [review]
🎆

**Pull request merged**
